### ISSUE TITLE
What to do

### ISSUE THREAD

**Issue by JoostK** [JonWallsten/monorepo-new#6]
Hi @JonWallsten,

it is not clear to me at all what to do to reproduce the timings you posted. I am getting errors in the `build` and `webpack` scripts and I don't know what timings to measure.

Additionally, the latest commit updates _everything_ at once, which prevents any sort of comparison between Angular v11 and v12. At this point I'm afraid this is not really actionable for us, given that the entire build pipeline appears custom except for the usage of `@ngtools/webpack` as a Webpack plugin. I'd like to isolate changes to that part only.

**Comment by JonWallsten** [comment]
@JoostK Can you post the errors? I worked fine for me locally. But I understand that different environments can give different results. 
All I did was to downgrade the Angular packages in the root package.json to reduce the build times again. 
I can create a new branch with that change to make it easier.
I also run "npm run reset" between the installations to remove all packages so I'm sure it's the correct angular version.

**Comment by JonWallsten** [comment]
@JoostK: Forgot to mention. Just use "npm run dev:edit". No point in starting multiple applications.

**Comment by JonWallsten** [comment]
Added this for your convenience:
https://github.com/JonWallsten/monorepo-new/tree/angular-11

**Comment by JoostK** [comment]
Thanks; on master (v12) the `nom run dev:edit` shows:

```
webpack 5.37.0 compiled with 5 warnings in 16692 ms
```

is that the number I should be watching?

**Comment by JonWallsten** [comment]
Yeah that's the time. Just be aware that it's building multiple packages. So make the time is connected to web-app-edit and not one of the libraires.

**Comment by JonWallsten** [comment]
I will run this myself again now to verify. But I've done it a few times already. But as you saw in my post in the issue, the worst part is the real project. And that I can't share. But I can help with debugging. I've messed around a lot in Chrome Dev Tools while debugging Protractor, Webpack and Angular (previous versions).

**Comment by JonWallsten** [comment]
Webpack 12:
webpack 5.33.2 compiled with 3 warnings in 38950 ms

**Comment by JoostK** [comment]
Okay these are my results:

v11; `$ packages/web-app-edit: nom run build:prod`:

~16s:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/123679/118485926-4aaf4d00-b719-11eb-9eda-5eda3db4d4f9.png">


v12; `$ packages/web-app-edit: nom run build:prod`:

~22s

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/123679/118486038-6fa3c000-b719-11eb-907e-1ca98662684e.png">

That big yellow block in v12 is dart-sass, which was the small purple block in v11. That accounts for the ~6s difference.

**Comment by JonWallsten** [comment]
That's interesting! How do I generate the same thing with our real project? The build time for `npm run build:dev` went from ~40 sec -> ~430 sec after upgrading.

**Comment by JoostK** [comment]
This is the relevant issue: angular/components#22676. I tried to convert your repro from `@import` to `@use` but that results in compilation errors. The CLI would migrated this but since you're not using the CLI those migrations haven't been applied.

**Comment by JoostK** [comment]
> That's interesting! How do I generate the same thing with our real project? The build time for `npm run build:dev` went from ~40 sec -> ~430 sec after upgrading.

I look at what binary is run behind the npm  script and then execute it using a debugger:

```bash
node --inspect-brk ./node_modules/.bin/webpack --config config/webpack.prod.ts --bail
```

Then open `chrome://inspect` -> "Open dedicated DevTools for Node" -> Profiler tab -> Record (this will resume from the halted debugger in profiling mode). Wait until it finishes and then stop recording, wait for it to process the recording to see the graph and only then quit the process.

**Comment by JonWallsten** [comment]
> This is the relevant issue: [angular/components#22676](https://github.com/angular/components/issues/22676). I tried to convert your repro from `@import` to `@use` but that results in compilation errors. The CLI would migrated this but since you're not using the CLI those migrations haven't been applied.

Ah, I see! What exactly is the CLI migrating? Is that something I can do manually in our project? I accept some manual labor since we have a special solution due to the nature of our project and a bunch of legacy stuff.

**Comment by JonWallsten** [comment]
> > That's interesting! How do I generate the same thing with our real project? The build time for `npm run build:dev` went from ~40 sec -> ~430 sec after upgrading.
> 
> I look at what binary is run behind the npm script and then execute it using a debugger:
> 
> ```shell
> node --inspect-brk ./node_modules/.bin/webpack --config config/webpack.prod.ts --bail
> ```
> 
> Then open `chrome://inspect` -> "Open dedicated DevTools for Node" -> Profiler tab -> Record (this will resume from the halted debugger in profiling mode). Wait until it finishes and then stop recording, wait for it to process the recording to see the graph and only then quit the process.

Ah, I suspected it was that easy. Wasn't sure you used some special profiling tool. I'll generate one and report ASAP.

**Comment by JoostK** [comment]
> > > That's interesting! How do I generate the same thing with our real project? The build time for `npm run build:dev` went from ~40 sec -> ~430 sec after upgrading.
> > 
> > 
> > I look at what binary is run behind the npm script and then execute it using a debugger:
> > ```shell
> > node --inspect-brk ./node_modules/.bin/webpack --config config/webpack.prod.ts --bail
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then open `chrome://inspect` -> "Open dedicated DevTools for Node" -> Profiler tab -> Record (this will resume from the halted debugger in profiling mode). Wait until it finishes and then stop recording, wait for it to process the recording to see the graph and only then quit the process.
> 
> Ah, I suspected it was that easy. Wasn't sure you used some special profiling tool. I'll generate one and report ASAP.

Keep in mind that you probably won't be able to capture the whole run; it'll likely reach memory limitations around 2 minutes of profiling or thereabouts. You might have more luck, but the Web Inspector sometimes just crashes when it can't handle it anymore.

**Comment by JoostK** [comment]
> > This is the relevant issue: [angular/components#22676](https://github.com/angular/components/issues/22676). I tried to convert your repro from `@import` to `@use` but that results in compilation errors. The CLI would migrated this but since you're not using the CLI those migrations haven't been applied.
> 
> Ah, I see! What exactly is the CLI migrating? Is that something I can do manually in our project? I accept some manual labor since we have a special solution due to the nature of our project and a bunch of legacy stuff.

I don't know anything about the migration.

**Comment by JonWallsten** [comment]
> Keep in mind that you probably won't be able to capture the whole run; it'll likely reach memory limitations around 2 minutes of profiling or thereabouts. You might have more luck, but the Web Inspector sometimes just crashes when it can't handle it anymore.

Yeah, we've had the same issue profiling memory issue in our own app. I can try to run in on one of our smaller apps instead if that's the case.

**Comment by JonWallsten** [comment]
![image](https://user-images.githubusercontent.com/5993909/118499181-f90dbf00-b726-11eb-8846-bbde83c4bf87.png)

**Comment by JonWallsten** [comment]
Had to stop the recording after a while. I get the same result as you. Something is wrong with SASS.

**Comment by Splaktar** [comment]
For the Angular Material migrations, there are two steps to move to the new Sass module system
1. The [`ng update` migration](https://github.com/angular/components/tree/master/src/material/schematics/ng-update/migrations/theming-api-v12)
1. Running [sass-migrator](https://sass-lang.com/documentation/cli/migrator) on your other Sass imports

**Comment by JonWallsten** [comment]
@clydin: I replaced all @import with @use in my project, but I get this error:
``` 
ERROR: packages\web-lib-angular\src\components\settings-dialog\settings-dialog.component.ts:60:17 - error NG2008: Could not find stylesheet file './settings-dialog.component.scss'.
60     styleUrls: ['packages\web-lib-angular\settings-dialog.component.scss'],
```

```
@Component({
    selector: 'settings-dialog',
    templateUrl: './settings-dialog.component.html',
    styleUrls: ['./settings-dialog.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
```

It resolves the file to the root of the library, but in relation to the monorepo root. So it's double wrong.
Is there something here I'm missing?

**Comment by Splaktar** [comment]
@JonWallsten it's not tested outside of the CLI, but the following might be workable

> The theming-api-v12 migration is written so it doesn't really depend on the CLI infrastructure: it reads in a string and it returns a string. They could take that file and run it through their repo.

So you'll have to come up with some of your own scripting, but the code in the migration could be usable outside of the Angular CLI.

**Comment by JonWallsten** [comment]
@Splaktar: Thanks! So something like this:
```
const paths = ['src/components/test-component/test-component.scss', 'src/styles/shared.scss'];
const foo = new ThemingApiMigration();
paths.forEach(path => {
  foo.visitStylesheet(path );
});
```
